spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/cosmic?useSSL=false
    username: cosmic
    password: cosmic
    driver-class-name: org.mariadb.jdbc.Driver

  elasticsearch:
    jest:
      uris: http://localhost:9200

cosmic:

  usage-api:
    scan-interval: "*/10 * * * * *"
