spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/cosmic?useSSL=false
    username: cosmic
    password: cosmic
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    elasticsearch:
      cluster-nodes: localhost:9300

cosmic:

  usage-api:
    scan-interval: "*/10 * * * * *"
