spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/cosmic?useSSL=false
    username: cosmic
    password: cosmic
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: cosmic-message-broker
    port: 5672
    username: cosmic
    password: cosmic

cosmic:

  metrics-collector:
    scan-interval: "*/10 * * * * *"
    broker-exchange: cosmic-metrics-exchange
    broker-exchange-key: cosmic-metrics-key
